kind: pipeline
name: default

steps:
  - name: build
    image: node:alpine
    commands:
      - yarn
      - yarn build
  - name: clean
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      username: drone
      port:
        from_secret: SSH_PORT
      key:
        from_secret: SSH
      script:
        - rm -rf /srv/http/092918.xyz/*
  - name: deploy
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: SSH_HOST
      username: drone
      port:
        from_secret: SSH_PORT
      key:
        from_secret: SSH
      target: /srv/http/092918.xyz/
      rm: false
      source: site/.vuepress/dist/
  - name: fix 
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      username: drone
      port:
        from_secret: SSH_PORT
      key:
        from_secret: SSH
      script:
        - mv /srv/http/092918.xyz/site/.vuepress/dist/* /srv/http/092918.xyz/
        - rm -rf /srv/http/092918.xyz/site/
