kind: pipeline
name: default

steps:
  - name: build
    image: node:alpine
    commands:
      - yarn
      - yarn build
      - mv site/.vuepress/dist 092918.xyz
  - name: clean
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      username: drone
      port:
        from_secret: SSH_PORT
      key:
        from_secret: SSH
      script:
        - rm -rf /srv/http/092918.xyz/*
  - name: deploy
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: SSH_HOST
      username: drone
      port:
        from_secret: SSH_PORT
      key:
        from_secret: SSH
      target: /srv/http
      source: 092918.xyz
